{{- $integrations := (default dict .Values.integrations) -}}
{{- $data := (default dict $integrations.jenkins) }}
{{- if $data }}
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: rhtap-jenkins-integration
stringData:
  baseUrl: {{ $data.baseUrl }}
  username: {{ $data.username }}
  token:  {{ $data.token }}
{{- end }}