apiVersion: v2
name: tssc-app-namespaces
description: Red Hat User Application Namespaces
type: application
version: "1.6.0"
annotations:
  tssc.redhat-appstudio.github.com/depends-on: tssc-acs, tssc-pipelines, tssc-tpa
